name: Add cool site and commit it
on:
  repository_dispatch:
    types: [update-inspirations]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  Add-cool-site:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull latest code
        run: git pull --rebase

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Add cool site from github webhook payload
        env:
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          GITHUB_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: npm run downloadCoolSites

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(content): Add cool site: ${{ github.event.client_payload.name }}"
          add: "src"
